---
title: Data Management FSS
date: 15/2/2023
---


# Data is essential in socio-scientific research.

To the extent that conclusions in socio-scientific research rely on data, this data must be diligently collected and must be traceable for those who wish to verify these conclusions. All data also has an important documentation function: data that is collected in the present can prove to be of great value to future research (provided the data has been carefully managed and documented).

The purpose of the [FSS Research Data Management policy][fss-rdm-policy] is therefore to encourage and facilitate its researchers to systematically and carefully collect, manage and archive their data and ensure that they adhere to the three principles of data management highlighted above: diligent collection, traceability and documentation.

On this Research Data Management theme page of FSS, you will find an overview of all relevant information, products and support services we provide throughout the research life cycle (in collaboration with other VU services).


## While writing your proposal

Whether you funder requires a full data management plan, a data management paragraph, or the completions of en ethics table, it is good to think about your data management while writing your proposal. Some questions you need to consider are:

- Will I collect new data, and if so, how will I manage, store and archive this data during the course of my research?
- Is the data personal data? How will I comply with GDPR?
- What are the ethical dimensions of my research?

To help you quickly write up these sections of your proposal, the Research Office provides the following documents:

- [Generic Data Management Paragraphs][genericparagraph] you can adapt to fit your research. These cover data management and privacy.
- [NWO Talent Scheme Explained][nwoguidance]: detailed guidance on how to fill out the data management section in your NWO proposal.
- [ERC Ethics Self-assessment explained][ercguidance]: detailed guidance on how to fill out the Ethics Table in your ERC proposal.

To be clear: you are only obliged to draft a data management paragraph in case a research funder explicitly asks for it. If this is not the case, or if you are preparing a research study without external funding, you can directly start developing a full data management plan.


## Before starting your research

In the proposal you roughly indicated how you will manage your data and deal with ethics and privacy issues; once your proposal is awarded you need to think about the details:

1. How you will deal with ethics issues, by going through [Ethics Review][rerc].
2. Where your data is stored, both during and after the research. We recommend [Yoda][yoda].
3. Compliance with GDPR. The most important part is thinking about your informed consent procedure.
4. Writing your Data Management Plan on [DMP Online][dmponline], and sharing it with colleagues so they can learn.

Full details on these four steps can be found in the page "[Starting a new project][fss-rdm-newproject]".


## During Research

You may find out during your research that you need to share your data with more people than you thought, that you needed more sensitive data than anticipated, or have to make other changes to your design. In these cases you should re-check the above four steps, and update your Data Management Plan if needed, so that it accurately reflects how you are dealing with your data.


## After Publication of your findings
All data collected by the VU should be stored for 10 years. For sensitive data (such as personal data) this can be done by adding it to a [Yoda][yoda] Vault. Data stored in the Vault can only be accessed for verification purposes. Non-sensitive data you can publish through Yoda, or through other VU-provided services such as OSF and DataVerseNL.

Like all other research outputs, your data sets should be registered in [PURE][pure], preferably with a persistent link or identifier; even if the data is not publicly available. 


## Support & Contact

You can get support and find more information in the following places:

- The [Faculty Data Steward][datasteward] (or the [RDM Support Desk][rdmsupport] in case you can't reach the data steward)
- The [RDM FAQ][fss-rdm-faq]
- The [Research Data Support Portal][rds-portal] (which contains links to all other VU-wide support there is on RDM)
- The [RDM Libguides][libguide]

<!--LINKS-->


<!-- Contacts -->

[rdmsupport]: mailto:RDM@vu.nl 
[datasteward]: mailto:k.leuveld@vu.nl
[privacychampion]: mailto:k.leuveld@vu.nl



<!-- Faculty Pages -->

[rerc]: https://vu.nl/en/employee/social-sciences-getting-started/research-ethics-review-fss
[self-check]: https://vuletteren.eu.qualtrics.com/jfe/form/SV_6hCj2czIWzboW6V
[fss-rdm-info]: https://vu.nl/en/employee/social-sciences-getting-started/data-management-fss
[fss-archiving]: https://github.com/kleuveld/rdm_pages/blob/fss_rdm_policy/_documents/fss_archiving_guidelines.md
[fss-rdm-policy]: https://assets.vu.nl/d8b6f1f5-816c-005b-1dc1-e363dd7ce9a5/4d95b39d-42d0-49c3-8797-382ed7767549/FSW%20Datamanagementbeleid%20ENG.pdf

[fss-rdm-newproject]: INSERTLINK
[fss-rdm-faq]: INSERTLINK



<!-- VU-wide Resources -->

[libguide]: https://libguides.vu.nl/rdm
[rds-portal]: https://vu.nl/nl/medewerker/research-data-support


<!-- Tools -->

[dmponline]: https://dmponline.vu.nl
[sdcmicro]: https://sdcpractice.readthedocs.io/en/latest/sdcMicro.html
[amnesia]: https://amnesia.openaire.eu/
[yoda]: https://portal.yoda.vu.nl
[storage-finder]: https://vu.nl/en/research/storagefinder
[cryptomator]: https://cryptomator.org/
[pure]: https://research.vu.nl/


<! Templates -->

[privacystatement_nl]: https://vunl.sharepoint.com/:w:/s/FSW-OE-ResearchOfficeFSS/ESBLrBcDrLhLpzfiVI8nHmUB76Deu6chNA3xehbSeOnemw?e=OA1jdu
[privacystatement_en]: https://vunl.sharepoint.com/:w:/s/FSW-OE-ResearchOfficeFSS/EYTq4TISYv5ElJJzSRxC7IcByRFwKCzlMy8EAiOvBXpZmw?e=PIN51k
[informedconsent_nl]: https://vunl.sharepoint.com/:w:/s/FSW-OE-ResearchOfficeFSS/ERBn_xahKvlLkDUK-U_tftEBotu01tkqAGJEmek6QaW7bA?e=bzCJmT
[informedconsent_en]: https://vunl.sharepoint.com/:w:/s/FSW-OE-ResearchOfficeFSS/EWwt5dMHAfJNgoKtxCfiwBYBi_vH0cad1g6XIrHhyFPE0g?e=zfMy3k


<!-- Examples -->

[genericparagraph]: https://vunl.sharepoint.com/:w:/s/FSW-OE-ResearchOfficeFSS/ESBLrBcDrLhLpzfiVI8nHmUB76Deu6chNA3xehbSeOnemw?e=nt570Y
[nwoguidance]: https://vunl.sharepoint.com/:w:/s/FSW-OE-ResearchOfficeFSS/EaM6nSsB16NNihVExSkXQPQBeVTPRnsaZTsH74qn9cZ_7w?e=JrQKG6
[ercguidance]: https://vunl.sharepoint.com/:w:/s/FSW-OE-ResearchOfficeFSS/EaM6nSsB16NNihVExSkXQPQBeVTPRnsaZTsH74qn9cZ_7w?e=JrQKG6