# FSS Policy Comparison: FAIR Principles

Source: https://www.go-fair.org/fair-principles/

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th><strong>Findable</strong></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>F1. (Meta)data are assigned a globally unique and persistent
identifier</td>
<td>FSS guidelines require data to be archived in a repository that
issues a unique and persistent identifier.</td>
</tr>
<tr class="even">
<td>F2. Data are described with rich metadata (defined by R1 below)</td>
<td>FSS guidelines are for researchers to do this on PURE (at a
minimum).</td>
</tr>
<tr class="odd">
<td>F3. Metadata clearly and explicitly include the identifier of the
data they describe</td>
<td>FSS guidelines are for researchers to do this on PURE (at a
minimum).</td>
</tr>
<tr class="even">
<td>F4. (Meta)data are registered or indexed in a searchable
resource</td>
<td>PURE meets this criterion.</td>
</tr>
<tr class="odd">
<td><strong>Accessible</strong></td>
<td></td>
</tr>
<tr class="even">
<td><p>A1. (Meta)data are retrievable by their identifier using a
standardised communications protocol</p>
<blockquote>
<p>A1.1 The protocol is open, free, and universally implementable</p>
<p>A1.2 The protocol allows for an authentication and authorisation
procedure, where necessary</p>
</blockquote></td>
<td>Public data repositories provide a link that works for this. For
private data, researchers have to provide persistent contact
details.</td>
</tr>
<tr class="odd">
<td>A2. Metadata are accessible, even when the data are no longer
available</td>
<td>FSS relies on PURE for this.</td>
</tr>
<tr class="even">
<td><strong><u>I</u>nteroperable</strong></td>
<td></td>
</tr>
<tr class="odd">
<td>I1. (Meta)data use a formal, accessible, shared, and broadly
applicable language for knowledge representation.</td>
<td>FSS does not have specific guidelines to ensure machine readability,
but does recommend all archiving to be done in English.</td>
</tr>
<tr class="even">
<td>I2. (Meta)data use vocabularies that follow FAIR principles</td>
<td>FSS requires all documentation to be uploaded in the same
repository, under the same identifier as the data.</td>
</tr>
<tr class="odd">
<td>I3. (Meta)data include qualified references to other (meta)data</td>
<td>FSS has no specific guidelines for this.</td>
</tr>
<tr class="even">
<td><strong>Re-usable</strong></td>
<td></td>
</tr>
<tr class="odd">
<td><p>R1. (Meta)data are richly described with a plurality of accurate
and relevant attributes</p>
<blockquote>
<p>R1.1. (Meta)data are released with a clear and accessible data usage
license</p>
<p>R1.2. (Meta)data are associated with detailed provenance</p>
<p>R1.3. (Meta)data meet domain-relevant community standards</p>
</blockquote></td>
<td><p>FSS requires all public data to include licenses , and all
personal data to have information about the informed consent
procedure.</p>
<p>Data that is not made publically available, but only archived for
verification purposes, should only be made available under strict data
transfer agreement that limit the use of data to the verification of the
findings of the original research.</p>
<p>To ensure provenance, FSS requires researchers to upload the rawest
data they can, and a description of all modification to this
data.</p></td>
</tr>
</tbody>
</table>
