# VU FSS guidelines for archiving data

**Note on this draft**: *This first draft is based on the Guideline for the archiving of academic research for faculties of behavioural and social sciences in the Netherlands (2022). They have been updated with qualitative data in mind, but input about ways to make these guidelines work better for the diversity of data we have in the faculty is welcome. Please contact k.leuveld@vu.nl with any comments or suggestions you may have.*

Researchers at the Faculty of Social Sciences are expected to archive "all data that can be reasonably deemed necessary to verify the findings of the research". These guidelines serve as practical advice on what to archive. The following materials should be archived, within one month after the publication date:

- A copy of the publication that uses the data.
- Raw data: unedited data files providing the most direct registration of the behaviour or reactions of test subjects/respondents. If the raw data files have been accessibly stored in an external archive (such as storage facilities at DANS), or if the data cannot be archived on university servers (for example due to IP restrictions) making reference to the location of the files will suffice. The VU researcher must ensure that such externally stored raw data will be available for verification purposes. Raw data may not be changed once they have been made digitally available.
- Analyzed data: the data files that were eventually analysed when preparing the article (e.g. an SPSS data file after transforming variables, after applying selections, etc.). This is not necessary if the raw data file was directly analysed, or if the analyzed data can be constructed without excessive effort from the raw data  (for example by running a script). 
- A description of the procedures to transform the raw data into analyzed data. This could be computer code (for example Atlas.ti, SPSS/JASP syntax file, MATLAB analysis scripts, R code) or a description of the steps taken in the qualitative analysis of primary research data, i.e. themes, domains, taxonomies, components.
- A description of the steps taken to process the analyzed data into results in the manuscript. This could be computer code or a description of the steps taken in the qualitative analysis of primary research data.
- Any documentation that can reasonably be deemed necessary in order for other researchers to understand the data and/or verify the research's findings. The precise documentation depends on the methods used, but examples include: study design documents, interview guides, questionnaires, surveys, and topic lists. The materials must be available in the
language in which the research was conducted.
- A readme file (metadata) describing which documents and files can be found where and how they should be interpreted. The readme file must be sufficiently clear, so that a relevant fellow researcher can verify the results discussed in the publication. The readme file must also contain the following information:
	- Name of the person who stored the documents or files 
	- Division of roles among authors, indicating at least who analysed the data 
	- Date on which the manuscript was accepted, including reference 
	- Date/period of data collection 
	- Names of people who collected the data 
	- If relevant: addresses of field locations where data were collected and contact persons (if any) 
	- Whether the data is made open or not and if not, a valid reason for not opening up the data
- Documents received from the Research Ethics Review Committee: at least the result of the self-check, and if applicable result from a full review.
- If using personal data: information about the informed consent procedure, such as a privacy statement, or a blank informed consent form.

